### ISSUE TITLE
Unexpected token {

### ISSUE THREAD

**Issue by sergionegri** [yo1dog/requestbin-curl#2]
I'm new to node so I could have made some silly mistake.
Steps taken:

- I've installed node: `sudo apt-get install -y nodejs`
- I've placed the requestbinCurl.js and .jshintrc in the same directory
- From that directory I called `node requestbinCurl.js https://requestb.in/1hscd6f1?inspect` 

I get:
const {rbBinId, rbRequestId} = result;
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

Thank you for your help

**Comment by yo1dog** [comment]
Your version of node is outdated (es6 features are not supported). I believe v6.0.0 would be the min version required, but you should update to the latest.

Also, only `requestbinCurl.js` is needed. `.jshintrc` is not.
